"""
Complete seed: all test questions and problems exported from production SQLite.
Auto-runs on startup via create_tables() -> _seed_visual_content().
"""

import json
from app.database.database import SessionLocal
from app.models.admin_test import AdminTestQuestion
from app.models.problem import Problem


ALL_TEST_QUESTIONS = [
    {
        "topic": "quantity",
        "question": "250-нің 12%-ы неге тең?",
        "option_a": "25",
        "option_b": "30",
        "option_c": "28",
        "option_d": "32",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "250 × 12/100 = 30.",
    },
    {
        "topic": "quantity",
        "question": "Егер $\\frac{3}{5} = \\frac{x}{20}$ болса, $x$ нешеге тең?",
        "option_a": "10",
        "option_b": "15",
        "option_c": "12",
        "option_d": "18",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "Айқас көбейту: 3 × 20 = 5x → x = 60/5 = 12.",
    },
    {
        "topic": "change_and_relationships",
        "question": "$3x - 7 = 14$ теңдеуін шешіңіз.",
        "option_a": "5",
        "option_b": "7",
        "option_c": "3",
        "option_d": "21",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "3x = 14 + 7 = 21, x = 21/3 = 7.",
    },
    {
        "topic": "change_and_relationships",
        "question": "$y = 2x + 1$ функциясының графигі қай нүктеден өтеді?",
        "option_a": "(0, 1)",
        "option_b": "(1, 0)",
        "option_c": "(0, 2)",
        "option_d": "(2, 0)",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "x = 0 болғанда y = 2(0) + 1 = 1, сондықтан (0, 1) нүктесі.",
    },
    {
        "topic": "space_and_shape",
        "question": "Қабырғасы 6 см квадраттың ауданы нешеге тең?",
        "option_a": "24 см²",
        "option_b": "36 см²",
        "option_c": "12 см²",
        "option_d": "48 см²",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "S = a² = 6² = 36 см².",
    },
    {
        "topic": "space_and_shape",
        "question": "Пифагор теоремасы бойынша, катеттері 5 және 12 болса, гипотенуза нешеге тең?",
        "option_a": "17",
        "option_b": "13",
        "option_c": "15",
        "option_d": "14",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "c = √(5² + 12²) = √(25 + 144) = √169 = 13.",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Деректер: 4, 7, 7, 9, 13. Медиана неге тең?",
        "option_a": "7",
        "option_b": "8",
        "option_c": "9",
        "option_d": "4",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "Реттелген қатарда ортаңғы мән 7.",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Монетаны 2 рет лақтырғанда екеуі де елтаңба болу ықтималдығы?",
        "option_a": "1/2",
        "option_b": "1/4",
        "option_c": "1/3",
        "option_d": "1/8",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "P = 1/2 × 1/2 = 1/4.",
    },
    {
        "topic": "change_and_relationships",
        "question": "$x^2 - 9 = 0$ теңдеуінің шешімдері қандай?",
        "option_a": "3 және -3",
        "option_b": "9 және -9",
        "option_c": "3 және 0",
        "option_d": "0 және -3",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "x² = 9, x = ±3.",
    },
    {
        "topic": "quantity",
        "question": "$2^5$ неге тең?",
        "option_a": "10",
        "option_b": "25",
        "option_c": "32",
        "option_d": "64",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "2⁵ = 2×2×2×2×2 = 32.",
    },
    {
        "topic": "space_and_shape",
        "question": "Радиусы 10 см шеңбердің ұзындығы нешеге тең? ($\\pi \\approx 3.14$)",
        "option_a": "31.4 см",
        "option_b": "62.8 см",
        "option_c": "314 см",
        "option_d": "20 см",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "C = 2πr = 2 × 3.14 × 10 = 62.8 см.",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Кәсіпорынның 5 жылдағы пайдасы (млн тг): 10, 15, 12, 18, 20. Орташа жылдық пайда?",
        "option_a": "12",
        "option_b": "15",
        "option_c": "18",
        "option_d": "20",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "Орташа = (10+15+12+18+20)/5 = 75/5 = 15 млн тг.",
    },
    {
        "topic": "quantity",
        "question": "$\\frac{2}{5}$ санын пайызбен жазыңыз.",
        "option_a": "20%",
        "option_b": "40%",
        "option_c": "25%",
        "option_d": "50%",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$\\frac{2}{5} = 0.4 = 40\\%$",
    },
    {
        "topic": "quantity",
        "question": "800-дің 15%-ын табыңыз.",
        "option_a": "100",
        "option_b": "120",
        "option_c": "150",
        "option_d": "80",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$800 \\times 0.15 = 120$",
    },
    {
        "topic": "quantity",
        "question": "Тауар бағасы 6000 тг-ден 7200 тг-ге көтерілді. Пайыздық өсім қанша?",
        "option_a": "15%",
        "option_b": "20%",
        "option_c": "25%",
        "option_d": "12%",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$(7200-6000)/6000 \\times 100 = 20\\%$",
    },
    {
        "topic": "quantity",
        "question": "$3^4$ неге тең?",
        "option_a": "12",
        "option_b": "64",
        "option_c": "81",
        "option_d": "27",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "$3^4 = 3 \\times 3 \\times 3 \\times 3 = 81$",
    },
    {
        "topic": "quantity",
        "question": "$\\sqrt{144}$ неге тең?",
        "option_a": "14",
        "option_b": "11",
        "option_c": "12",
        "option_d": "13",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "$12 \\times 12 = 144$, сондықтан $\\sqrt{144} = 12$",
    },
    {
        "topic": "quantity",
        "question": "$\\frac{5}{8} - \\frac{1}{4}$ неге тең?",
        "option_a": "$\\frac{3}{8}$",
        "option_b": "$\\frac{4}{8}$",
        "option_c": "$\\frac{1}{2}$",
        "option_d": "$\\frac{3}{4}$",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "$\\frac{5}{8} - \\frac{2}{8} = \\frac{3}{8}$",
    },
    {
        "topic": "quantity",
        "question": "Жұмысшы сағатына 1500 тг алады. 8 сағат жұмыс істесе, қанша алады?",
        "option_a": "10000",
        "option_b": "12000",
        "option_c": "11000",
        "option_d": "13000",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$1500 \\times 8 = 12000$ тг",
    },
    {
        "topic": "quantity",
        "question": "$0.75$ санын бөлшек түрінде жазыңыз.",
        "option_a": "$\\frac{1}{4}$",
        "option_b": "$\\frac{7}{10}$",
        "option_c": "$\\frac{3}{4}$",
        "option_d": "$\\frac{4}{5}$",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "$0.75 = \\frac{75}{100} = \\frac{3}{4}$",
    },
    {
        "topic": "change_and_relationships",
        "question": "$5x - 3 = 22$ теңдеуін шешіңіз.",
        "option_a": "3",
        "option_b": "4",
        "option_c": "5",
        "option_d": "6",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "$5x = 25$, $x = 5$",
    },
    {
        "topic": "change_and_relationships",
        "question": "$y = -x + 5$ функциясының $x = 3$ болғандағы мәнін табыңыз.",
        "option_a": "8",
        "option_b": "2",
        "option_c": "-2",
        "option_d": "3",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$y = -3 + 5 = 2$",
    },
    {
        "topic": "change_and_relationships",
        "question": "$x^2 - 16 = 0$ теңдеуінің оң түбірін табыңыз.",
        "option_a": "2",
        "option_b": "8",
        "option_c": "4",
        "option_d": "16",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "$x^2 = 16$, $x = \\pm 4$. Оң түбір: $4$",
    },
    {
        "topic": "change_and_relationships",
        "question": "Арифметикалық прогрессияда $a_1=2$, $d=3$. $a_5$ табыңыз.",
        "option_a": "14",
        "option_b": "17",
        "option_c": "11",
        "option_d": "12",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "$a_5 = 2 + (5-1) \\cdot 3 = 2 + 12 = 14$",
    },
    {
        "topic": "change_and_relationships",
        "question": "$2(x+3) = 14$ теңдеуін шешіңіз.",
        "option_a": "5",
        "option_b": "4",
        "option_c": "7",
        "option_d": "3",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$x + 3 = 7$, $x = 4$",
    },
    {
        "topic": "change_and_relationships",
        "question": "$f(x) = x^2 - 1$ функциясы үшін $f(3)$ мәнін табыңыз.",
        "option_a": "8",
        "option_b": "10",
        "option_c": "6",
        "option_d": "9",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "$f(3) = 9 - 1 = 8$",
    },
    {
        "topic": "change_and_relationships",
        "question": "Теңдеулер жүйесін шешіңіз: $x + y = 10$, $x - y = 4$. $x$ неге тең?",
        "option_a": "6",
        "option_b": "7",
        "option_c": "8",
        "option_d": "5",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "Қосамыз: $2x = 14$, $x = 7$",
    },
    {
        "topic": "change_and_relationships",
        "question": "Геометриялық прогрессияда $b_1=3$, $q=2$. $b_4$ табыңыз.",
        "option_a": "12",
        "option_b": "18",
        "option_c": "24",
        "option_d": "48",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "$b_4 = 3 \\cdot 2^3 = 3 \\cdot 8 = 24$",
    },
    {
        "topic": "space_and_shape",
        "question": "Тіктөртбұрыштың ұзындығы 12 см, ені 5 см. Периметрін табыңыз.",
        "option_a": "34 см",
        "option_b": "60 см",
        "option_c": "17 см",
        "option_d": "24 см",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "$P = 2(12+5) = 2 \\cdot 17 = 34$ см",
    },
    {
        "topic": "space_and_shape",
        "question": "Үшбұрыштың бұрыштары $40°$, $60°$ және $x°$. $x$ неге тең?",
        "option_a": "100",
        "option_b": "90",
        "option_c": "80",
        "option_d": "70",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "$40 + 60 + x = 180$, $x = 80°$",
    },
    {
        "topic": "space_and_shape",
        "question": "Шардың радиусы 3 см. Көлемін табыңыз. ($\\pi \\approx 3.14$)",
        "option_a": "113.04 см³",
        "option_b": "28.26 см³",
        "option_c": "84.78 см³",
        "option_d": "36 см³",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "$V = \\frac{4}{3}\\pi r^3 = \\frac{4}{3} \\cdot 3.14 \\cdot 27 \\approx 113.04$ см³",
    },
    {
        "topic": "space_and_shape",
        "question": "$A(2, 3)$ және $B(6, 3)$ нүктелерінің ортасын табыңыз.",
        "option_a": "(4, 3)",
        "option_b": "(3, 3)",
        "option_c": "(4, 6)",
        "option_d": "(8, 6)",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "$M = (\\frac{2+6}{2}, \\frac{3+3}{2}) = (4, 3)$",
    },
    {
        "topic": "space_and_shape",
        "question": "Цилиндрдің радиусы 5 см, биіктігі 10 см. Көлемін табыңыз. ($\\pi \\approx 3.14$)",
        "option_a": "785 см³",
        "option_b": "628 см³",
        "option_c": "1570 см³",
        "option_d": "314 см³",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "$V = \\pi r^2 h = 3.14 \\cdot 25 \\cdot 10 = 785$ см³",
    },
    {
        "topic": "space_and_shape",
        "question": "Ромбтың диагональдары 6 см және 8 см. Ауданын табыңыз.",
        "option_a": "48 см²",
        "option_b": "24 см²",
        "option_c": "14 см²",
        "option_d": "28 см²",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$S = \\frac{d_1 \\cdot d_2}{2} = \\frac{6 \\cdot 8}{2} = 24$ см²",
    },
    {
        "topic": "space_and_shape",
        "question": "Трапецияның параллель қабырғалары 10 см және 6 см, биіктігі 4 см. Ауданын табыңыз.",
        "option_a": "64 см²",
        "option_b": "32 см²",
        "option_c": "40 см²",
        "option_d": "24 см²",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$S = \\frac{(a+b)}{2} \\cdot h = \\frac{16}{2} \\cdot 4 = 32$ см²",
    },
    {
        "topic": "space_and_shape",
        "question": "Конустың радиусы 4 см, биіктігі 9 см. Көлемін табыңыз. ($\\pi \\approx 3.14$)",
        "option_a": "150.72 см³",
        "option_b": "452.16 см³",
        "option_c": "100.48 см³",
        "option_d": "75.36 см³",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "$V = \\frac{1}{3}\\pi r^2 h = \\frac{1}{3} \\cdot 3.14 \\cdot 16 \\cdot 9 \\approx 150.72$ см³",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Деректер: 3, 5, 7, 9, 11. Медиана неге тең?",
        "option_a": "5",
        "option_b": "7",
        "option_c": "9",
        "option_d": "6",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "Реттелген қатардың ортаңғы мәні: 7",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Сынып оқушыларының 60%-ы ұл балалар. Сыныпта 30 оқушы болса, қыз балалар саны?",
        "option_a": "18",
        "option_b": "15",
        "option_c": "12",
        "option_d": "10",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "Қыздар: $30 \\times 0.4 = 12$",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Деректер жинағы: 4, 6, 6, 8, 10, 12. Арифметикалық ортасы?",
        "option_a": "7",
        "option_b": "7.67",
        "option_c": "8",
        "option_d": "6",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$(4+6+6+8+10+12)/6 = 46/6 \\approx 7.67$",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "52 карталы дестеден 1 карта алынады. Пік алу ықтималдығы?",
        "option_a": "$\\frac{1}{2}$",
        "option_b": "$\\frac{1}{13}$",
        "option_c": "$\\frac{1}{4}$",
        "option_d": "$\\frac{1}{52}$",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "Пік масті: 13 карта. $P = \\frac{13}{52} = \\frac{1}{4}$",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "10, 20, 30, 40, 50 деректерінің ауқымын (Range) табыңыз.",
        "option_a": "50",
        "option_b": "30",
        "option_c": "40",
        "option_d": "20",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "$R = x_{max} - x_{min} = 50 - 10 = 40$",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "3 монетаны лақтырғанда кемінде 1 елтаңба болу ықтималдығы?",
        "option_a": "$\\frac{7}{8}$",
        "option_b": "$\\frac{3}{4}$",
        "option_c": "$\\frac{1}{2}$",
        "option_d": "$\\frac{5}{8}$",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "$P = 1 - P(\\text{ешбір елтаңба жоқ}) = 1 - \\frac{1}{8} = \\frac{7}{8}$",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Деректер: 2, 2, 3, 4, 4, 4, 5. Мода мен медиананы табыңыз.",
        "option_a": "Мода=4, Медиана=4",
        "option_b": "Мода=2, Медиана=3",
        "option_c": "Мода=4, Медиана=3",
        "option_d": "Мода=3, Медиана=4",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "4 ең жиі кездеседі (3 рет) → мода=4. Ортаңғы мән → медиана=4",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Дүкеннің 5 күндік сатылымы: 100, 150, 200, 120, 180 мың тг. Орташа күндік сатылым?",
        "option_a": "140",
        "option_b": "150",
        "option_c": "160",
        "option_d": "170",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$(100+150+200+120+180)/5 = 750/5 = 150$ мың тг",
    },
    {
        "topic": "quantity",
        "question": "25 + 37 неге тең?",
        "option_a": "52",
        "option_b": "62",
        "option_c": "72",
        "option_d": "42",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "25 + 37 = 62",
    },
    {
        "topic": "quantity",
        "question": "100-дің жартысы?",
        "option_a": "25",
        "option_b": "75",
        "option_c": "50",
        "option_d": "40",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "100/2 = 50",
    },
    {
        "topic": "quantity",
        "question": "1 км неше метр?",
        "option_a": "10",
        "option_b": "100",
        "option_c": "1000",
        "option_d": "10000",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "1 км = 1000 м",
    },
    {
        "topic": "change_and_relationships",
        "question": "x + 5 = 12 болса, x = ?",
        "option_a": "5",
        "option_b": "7",
        "option_c": "17",
        "option_d": "6",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "x = 12 - 5 = 7",
    },
    {
        "topic": "change_and_relationships",
        "question": "Тізбек: 2, 4, 6, 8, ...?",
        "option_a": "9",
        "option_b": "12",
        "option_c": "10",
        "option_d": "11",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "Жұп сандар, келесі: 10",
    },
    {
        "topic": "space_and_shape",
        "question": "Квадрат қабырғасы 4 см. Периметрі?",
        "option_a": "8 см",
        "option_b": "12 см",
        "option_c": "16 см",
        "option_d": "20 см",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "P = 4 × 4 = 16 см",
    },
    {
        "topic": "space_and_shape",
        "question": "Тіктөртбұрыш 6×3. Ауданы?",
        "option_a": "9",
        "option_b": "18",
        "option_c": "12",
        "option_d": "24",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "S = 6 × 3 = 18",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Бой: 140,145,150,155,160. Ауқымы?",
        "option_a": "15",
        "option_b": "20",
        "option_c": "25",
        "option_d": "10",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "160 - 140 = 20",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Монета лақтыру — елтаңба ықтималдығы?",
        "option_a": "1/4",
        "option_b": "1/3",
        "option_c": "1/2",
        "option_d": "2/3",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "P = 1/2",
    },
    {
        "topic": "quantity",
        "question": "Кітап 2400 тг. 30% жеңілдікпен?",
        "option_a": "720",
        "option_b": "1680",
        "option_c": "1920",
        "option_d": "1200",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "2400 × 0.7 = 1680",
    },
    {
        "topic": "quantity",
        "question": "3/4 × 2/5 = ?",
        "option_a": "6/20",
        "option_b": "5/9",
        "option_c": "3/10",
        "option_d": "6/9",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "6/20 = 3/10",
    },
    {
        "topic": "change_and_relationships",
        "question": "3x + 2 = 2x + 7. x = ?",
        "option_a": "3",
        "option_b": "5",
        "option_c": "9",
        "option_d": "7",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "x = 5",
    },
    {
        "topic": "change_and_relationships",
        "question": "y = x² болғанда x = -3, y = ?",
        "option_a": "-9",
        "option_b": "9",
        "option_c": "6",
        "option_d": "-6",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "y = 9",
    },
    {
        "topic": "space_and_shape",
        "question": "Үшбұрыш: табан 10, биіктік 6. Ауданы?",
        "option_a": "60",
        "option_b": "16",
        "option_c": "30",
        "option_d": "40",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "S = ½×10×6 = 30",
    },
    {
        "topic": "space_and_shape",
        "question": "Диаметр 14 см. Радиус?",
        "option_a": "28",
        "option_b": "7",
        "option_c": "14",
        "option_d": "3.5",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "r = 14/2 = 7",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Зар: 3-тен үлкен сан ықтималдығы?",
        "option_a": "1/6",
        "option_b": "1/3",
        "option_c": "1/2",
        "option_d": "2/3",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "4,5,6 → P = 3/6 = 1/2",
    },
    {
        "topic": "quantity",
        "question": "8000 тг → -20% → +10%. Соңғы баға?",
        "option_a": "7040",
        "option_b": "7200",
        "option_c": "6400",
        "option_d": "7600",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "8000×0.8=6400, ×1.1=7040",
    },
    {
        "topic": "change_and_relationships",
        "question": "x² + 2x - 15 = 0. Түбірлер көбейтіндісі?",
        "option_a": "15",
        "option_b": "-15",
        "option_c": "2",
        "option_d": "-2",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "Виет: c/a = -15",
    },
    {
        "topic": "change_and_relationships",
        "question": "f(x) = 2x² - 3x + 1. f(2) = ?",
        "option_a": "3",
        "option_b": "5",
        "option_c": "7",
        "option_d": "1",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "8-6+1 = 3",
    },
    {
        "topic": "space_and_shape",
        "question": "A(0,0), B(6,0), C(6,8). Үшбұрыш ауданы?",
        "option_a": "48",
        "option_b": "24",
        "option_c": "14",
        "option_d": "28",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "S = ½×6×8 = 24",
    },
    {
        "topic": "space_and_shape",
        "question": "Параллелепипед 4×5×6. Бет ауданы?",
        "option_a": "148",
        "option_b": "120",
        "option_c": "74",
        "option_d": "240",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "2(20+30+24) = 148",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "12,15,18,20,25. Орташа=18. Дисперсия?",
        "option_a": "19.6",
        "option_b": "18",
        "option_c": "16.4",
        "option_d": "22",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "(36+9+0+4+49)/5 = 19.6",
    },
    {
        "topic": "quantity",
        "question": "200000 тг, 12%, 3 жыл күрделі пайыз?",
        "option_a": "280986",
        "option_b": "272000",
        "option_c": "281216",
        "option_d": "275000",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "200000×1.12³ ≈ 281216",
    },
    {
        "topic": "change_and_relationships",
        "question": "x² - 5x + 6 < 0 шешімі?",
        "option_a": "x<2 не x>3",
        "option_b": "2<x<3",
        "option_c": "x<-2 не x>-3",
        "option_d": "-3<x<-2",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "(x-2)(x-3)<0 → 2<x<3",
    },
    {
        "topic": "space_and_shape",
        "question": "Үшбұрыш 7,8,9. Герон ауданы?",
        "option_a": "12√5",
        "option_b": "6√5",
        "option_c": "26.83",
        "option_d": "28",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "p=12, S≈26.83",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "P(A)=0.6, P(B)=0.3, тәуелсіз. P(A∪B)?",
        "option_a": "0.9",
        "option_b": "0.72",
        "option_c": "0.18",
        "option_d": "0.48",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "0.6+0.3-0.18=0.72",
    },
    {
        "topic": "quantity",
        "question": "log₂32 + log₃27 = ?",
        "option_a": "7",
        "option_b": "8",
        "option_c": "9",
        "option_d": "6",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "5+3=8",
    },
    {
        "topic": "change_and_relationships",
        "question": "f(x)=x³-3x экстремумдары?",
        "option_a": "x=±1",
        "option_b": "x=0,3",
        "option_c": "x=±3",
        "option_d": "x=1,-3",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "f'=3x²-3=0 → x=±1",
    },
    {
        "topic": "space_and_shape",
        "question": "a=(3,4), b=(1,-2). Скаляр көбейтінді?",
        "option_a": "7",
        "option_b": "-5",
        "option_c": "1",
        "option_d": "11",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "3-8=-5",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "10 монета, дәл 3 елтаңба ықтималдығы?",
        "option_a": "0.300",
        "option_b": "0.250",
        "option_c": "0.117",
        "option_d": "0.150",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "C(10,3)/1024≈0.117",
    },
    {
        "topic": "quantity",
        "question": "1+2+3+...+100 = ?",
        "option_a": "5000",
        "option_b": "5050",
        "option_c": "10000",
        "option_d": "10100",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "100×101/2=5050",
    },
    {
        "topic": "change_and_relationships",
        "question": "lim(x→0) sin(x)/x = ?",
        "option_a": "0",
        "option_b": "∞",
        "option_c": "1",
        "option_d": "жоқ",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "Бірінші тамаша шек = 1",
    },
    {
        "topic": "space_and_shape",
        "question": "sin²α + cos²α = ?",
        "option_a": "0",
        "option_b": "2",
        "option_c": "1",
        "option_d": "sin2α",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "Тригонометриялық тепе-теңдік = 1",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Байес: P(A)=0.4, P(B|A)=0.5, P(B|Ā)=0.2. P(A|B)?",
        "option_a": "0.625",
        "option_b": "0.5",
        "option_c": "0.4",
        "option_d": "0.714",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "P(B)=0.32, P(A|B)=0.2/0.32=0.625",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Кестеде сынып оқушыларының математикадан алған бағалары берілген. Оқушылардың орташа бағасы нешеге тең?",
        "option_a": "3,6",
        "option_b": "4,0",
        "option_c": "3,8",
        "option_d": "4,2",
        "correct_option": "B",
        "difficulty": "2",
        "explanation": "Орташа = (3+5+4+4+2+5+4+3+5+5)/10 = 40/10 = 4,0.",
        "table_data": {"headers": ["Оқушы", "Баға"], "rows": [["Айгүл", "3"], ["Болат", "5"], ["Сара", "4"], ["Дамир", "4"], ["Ерлан", "2"], ["Жанна", "5"], ["Қайрат", "4"], ["Ләззат", "3"], ["Мадина", "5"], ["Нұрлан", "5"]], "caption": "Математика бағалары"},
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Кестеде дүкендегі сатылымдар көрсетілген. Қай күні ең көп сатылым болған?",
        "option_a": "Дүйсенбі",
        "option_b": "Сәрсенбі",
        "option_c": "Жұма",
        "option_d": "Сенбі",
        "correct_option": "D",
        "difficulty": "1",
        "explanation": "Сенбіде 87 бірлік сатылған — бұл ең жоғары көрсеткіш.",
        "table_data": {"headers": ["Күн", "Сатылым (бірлік)"], "rows": [["Дүйсенбі", "45"], ["Сейсенбі", "52"], ["Сәрсенбі", "61"], ["Бейсенбі", "58"], ["Жұма", "73"], ["Сенбі", "87"], ["Жексенбі", "65"]], "caption": "Апталық сатылым"},
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Кестеде оқушылардың бойлары берілген (см). Медианасын табыңыз.",
        "option_a": "162",
        "option_b": "165",
        "option_c": "164",
        "option_d": "168",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "Реттелген қатар: 155, 158, 162, 164, 165, 170, 175. Ортаңғы мән = 164.",
        "table_data": {"headers": ["Оқушы", "Бой (см)"], "rows": [["Асыл", "170"], ["Бақыт", "155"], ["Гүлнар", "162"], ["Дана", "175"], ["Елдос", "158"], ["Жасмин", "165"], ["Қанат", "164"]], "caption": "Оқушылардың бойлары"},
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Кестеде спорт секциясындағы оқушылар саны берілген. Барлық оқушылардың неше пайызы футбол ойнайды?",
        "option_a": "25%",
        "option_b": "30%",
        "option_c": "35%",
        "option_d": "40%",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "Барлығы: 30+20+25+15+10 = 100. Футбол: 30. Пайызы: 30/100 × 100% = 30%.",
        "table_data": {"headers": ["Спорт түрі", "Оқушы саны"], "rows": [["Футбол", "30"], ["Волейбол", "20"], ["Баскетбол", "25"], ["Жүзу", "15"], ["Теннис", "10"]], "caption": "Спорт секциялары"},
    },
    {
        "topic": "quantity",
        "question": "Кестеде жемістердің бағалары берілген. 3 кг алма мен 2 кг банан сатып алсаңыз, қанша төлейсіз?",
        "option_a": "2800 тг",
        "option_b": "3100 тг",
        "option_c": "2950 тг",
        "option_d": "3250 тг",
        "correct_option": "A",
        "difficulty": "2",
        "explanation": "3 × 600 + 2 × 500 = 1800 + 1000 = 2800 тг.",
        "table_data": {"headers": ["Жеміс", "Бағасы (1 кг)"], "rows": [["Алма", "600 тг"], ["Банан", "500 тг"], ["Апельсин", "750 тг"], ["Жүзім", "900 тг"]], "caption": "Жемістер бағасы"},
    },
    {
        "topic": "quantity",
        "question": "Кестеде 4 қаланың халық саны берілген. Барлық қалалардың жалпы халық саны қанша?",
        "option_a": "3 200 000",
        "option_b": "3 450 000",
        "option_c": "3 500 000",
        "option_d": "3 650 000",
        "correct_option": "C",
        "difficulty": "1",
        "explanation": "1 200 000 + 900 000 + 800 000 + 600 000 = 3 500 000.",
        "table_data": {"headers": ["Қала", "Халық саны"], "rows": [["Алматы", "1 200 000"], ["Астана", "900 000"], ["Шымкент", "800 000"], ["Ақтобе", "600 000"]], "caption": "Қалалар халқы"},
    },
    {
        "topic": "quantity",
        "question": "Кестеде тауарлардың бағасы мен жеңілдігі берілген. Жеңілдіктен кейін кроссовка қанша тұрады?",
        "option_a": "13 500 тг",
        "option_b": "12 000 тг",
        "option_c": "14 250 тг",
        "option_d": "11 250 тг",
        "correct_option": "A",
        "difficulty": "3",
        "explanation": "Кроссовка: 18 000 тг, жеңілдік 25%. 18 000 × 0.25 = 4 500. 18 000 − 4 500 = 13 500 тг.",
        "table_data": {"headers": ["Тауар", "Бағасы", "Жеңілдік"], "rows": [["Футболка", "5 000 тг", "10%"], ["Кроссовка", "18 000 тг", "25%"], ["Джинсы", "12 000 тг", "15%"], ["Куртка", "25 000 тг", "20%"]], "caption": "Жеңілдіктер"},
    },
    {
        "topic": "change_and_relationships",
        "question": "Кестеде $x$ пен $y$ мәндері берілген. $y = kx + b$ сызықтық функциясында $k$ коэффициентін табыңыз.",
        "option_a": "2",
        "option_b": "3",
        "option_c": "4",
        "option_d": "5",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$k = \\frac{y_2 - y_1}{x_2 - x_1} = \\frac{8 - 5}{2 - 1} = 3$.",
        "table_data": {"headers": ["x", "y"], "rows": [["0", "2"], ["1", "5"], ["2", "8"], ["3", "11"], ["4", "14"]], "caption": "Функция мәндері"},
    },
    {
        "topic": "change_and_relationships",
        "question": "Кестеде автомобильдің жүрген уақыты мен жолы берілген. 6 сағатта қанша км жол жүреді?",
        "option_a": "420 км",
        "option_b": "480 км",
        "option_c": "360 км",
        "option_d": "540 км",
        "correct_option": "A",
        "difficulty": "2",
        "explanation": "Жылдамдық = 140/2 = 70 км/сағ. 6 сағатта: 70 × 6 = 420 км.",
        "table_data": {"headers": ["Уақыт (сағ)", "Жол (км)"], "rows": [["1", "70"], ["2", "140"], ["3", "210"], ["4", "280"]], "caption": "Автомобиль қозғалысы"},
    },
    {
        "topic": "change_and_relationships",
        "question": "Кестеде тізбектің мүшелері берілген. 7-ші мүше нешеге тең?",
        "option_a": "128",
        "option_b": "96",
        "option_c": "112",
        "option_d": "64",
        "correct_option": "A",
        "difficulty": "4",
        "explanation": "Геометриялық тізбек: $a_n = 2^n$. $a_7 = 2^7 = 128$.",
        "table_data": {"headers": ["n", "$a_n$"], "rows": [["1", "2"], ["2", "4"], ["3", "8"], ["4", "16"], ["5", "32"]], "caption": "Тізбек мүшелері"},
    },
    {
        "topic": "space_and_shape",
        "question": "Кестеде фигуралардың өлшемдері берілген. Тіктөртбұрыштың ауданы мен шеңбердің ауданы арасындағы айырмашылық қанша? ($\\pi \\approx 3.14$)",
        "option_a": "$21.5$ см²",
        "option_b": "$19.74$ см²",
        "option_c": "$22.86$ см²",
        "option_d": "$18.44$ см²",
        "correct_option": "C",
        "difficulty": "4",
        "explanation": "Тіктөртбұрыш: $S = 8 \\times 6 = 48$ см². Шеңбер: $S = \\pi r^2 = 3.14 \\times 2.83^2 \\approx 25.14$ см². Айырма: $48 - 25.14 = 22.86$ см².",
        "table_data": {"headers": ["Фигура", "Өлшемі"], "rows": [["Тіктөртбұрыш", "8 см × 6 см"], ["Шеңбер", "r = 2.83 см"], ["Үшбұрыш", "табаны 10 см, биіктігі 7 см"]], "caption": "Фигуралар өлшемдері"},
    },
    {
        "topic": "space_and_shape",
        "question": "Кестеде 3 бөлменің өлшемдері берілген. Барлық бөлмелердің жалпы ауданы нешеге тең?",
        "option_a": "42 м²",
        "option_b": "45 м²",
        "option_c": "48 м²",
        "option_d": "50 м²",
        "correct_option": "C",
        "difficulty": "2",
        "explanation": "Зал: 5×4 = 20 м². Жатын бөлме: 4×4 = 16 м². Ас бөлме: 4×3 = 12 м². Барлығы: 20+16+12 = 48 м².",
        "table_data": {"headers": ["Бөлме", "Ұзындығы", "Ені"], "rows": [["Зал", "5 м", "4 м"], ["Жатын бөлме", "4 м", "4 м"], ["Ас бөлме", "4 м", "3 м"]], "caption": "Үй жоспары"},
    },
    {
        "topic": "space_and_shape",
        "question": "Суреттегі тең қабырғалы үшбұрыштың қабырғасы 10 см. Периметрін табыңыз.",
        "option_a": "20 см",
        "option_b": "30 см",
        "option_c": "40 см",
        "option_d": "25 см",
        "correct_option": "B",
        "difficulty": "1",
        "explanation": "Тең қабырғалы үшбұрыштың периметрі: P = 3a = 3 × 10 = 30 см.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Triangle.Equilateral.svg/320px-Triangle.Equilateral.svg.png",
    },
    {
        "topic": "space_and_shape",
        "question": "Суреттегі параллелограмның табаны 12 см, биіктігі 5 см. Ауданын табыңыз.",
        "option_a": "60 см²",
        "option_b": "48 см²",
        "option_c": "72 см²",
        "option_d": "34 см²",
        "correct_option": "A",
        "difficulty": "2",
        "explanation": "$S = a \\times h = 12 \\times 5 = 60$ см².",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Parallelogram_area.svg/320px-Parallelogram_area.svg.png",
    },
    {
        "topic": "space_and_shape",
        "question": "Суреттегі трапецияның параллель қабырғалары 8 см және 14 см, биіктігі 6 см. Ауданын табыңыз.",
        "option_a": "56 см²",
        "option_b": "66 см²",
        "option_c": "72 см²",
        "option_d": "84 см²",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "$S = \\frac{(a+b)}{2} \\times h = \\frac{(8+14)}{2} \\times 6 = \\frac{22}{2} \\times 6 = 66$ см².",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Trapezoid.svg/320px-Trapezoid.svg.png",
    },
    {
        "topic": "space_and_shape",
        "question": "Суреттегі цилиндрдің радиусы 3 см, биіктігі 10 см. Көлемін табыңыз. ($\\pi \\approx 3.14$)",
        "option_a": "282.6 см³",
        "option_b": "188.4 см³",
        "option_c": "314 см³",
        "option_d": "94.2 см³",
        "correct_option": "A",
        "difficulty": "4",
        "explanation": "$V = \\pi r^2 h = 3.14 \\times 9 \\times 10 = 282.6$ см³.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Cylinder_geometry.svg/220px-Cylinder_geometry.svg.png",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Суреттегі дөңгелек диаграммада оқушылардың сүйікті пәндері көрсетілген. Математиканы 90 оқушы таңдаған. Барлық оқушылар саны нешеге тең, егер математика үлесі 30% болса?",
        "option_a": "250",
        "option_b": "300",
        "option_c": "270",
        "option_d": "350",
        "correct_option": "B",
        "difficulty": "3",
        "explanation": "30% = 90 оқушы. 100% = 90 / 0.3 = 300 оқушы.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Pie_chart_EP_election_2004.svg/320px-Pie_chart_EP_election_2004.svg.png",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Суреттегі бағаналы диаграммада 5 айдың жауын-шашын мөлшері көрсетілген. Ең аз жауын-шашын қай айда болған?",
        "option_a": "Қаңтар",
        "option_b": "Наурыз",
        "option_c": "Шілде",
        "option_d": "Қыркүйек",
        "correct_option": "C",
        "difficulty": "1",
        "explanation": "Диаграмма бойынша шілде айында жауын-шашын ең аз.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Bar_chart_of_the_population_of_countries_bordering_Austria.svg/400px-Bar_chart_of_the_population_of_countries_bordering_Austria.svg.png",
    },
    {
        "topic": "change_and_relationships",
        "question": "Суреттегі координата жазықтығында $y = x + 2$ сызығы берілген. Бұл сызық $y$ осін қай нүктеде қиады?",
        "option_a": "(0, 1)",
        "option_b": "(0, 2)",
        "option_c": "(2, 0)",
        "option_d": "(0, -2)",
        "correct_option": "B",
        "difficulty": "2",
        "explanation": "$x = 0$ болғанда $y = 0 + 2 = 2$. Сондықтан $(0, 2)$ нүктесінде.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Cartesian-coordinate-system.svg/354px-Cartesian-coordinate-system.svg.png",
    },
    {
        "topic": "change_and_relationships",
        "question": "Суреттегі парабола $y = x^2$ функциясының графигі. $x = -3$ болғанда $y$ нешеге тең?",
        "option_a": "6",
        "option_b": "-9",
        "option_c": "9",
        "option_d": "-6",
        "correct_option": "C",
        "difficulty": "3",
        "explanation": "$y = (-3)^2 = 9$.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Quadratic_function_graph_%28y%3Dx%5E2%29.svg/320px-Quadratic_function_graph_%28y%3Dx%5E2%29.svg.png",
    },
]


ALL_PROBLEMS = [
    {
        "topic": "quantity",
        "question": "Дүкенде тауар бағасы 20%-ға арзандады. Бастапқы бағасы 5000 теңге болса, жаңа бағасын табыңыз.",
        "formula": "P_{жаңа} = P \\cdot (1 - \\frac{d}{100})",
        "correct_answer": "4000",
        "solution": "Жеңілдік: 5000 × 20/100 = 1000 теңге. Жаңа баға: 5000 - 1000 = 4000 теңге.",
        "difficulty": "1",
        "tags": ["пайыз", "бағалау"],
    },
    {
        "topic": "quantity",
        "question": "Рецептте 4 адамға 600 г ұн керек. 6 адамға қанша ұн керек?",
        "formula": "\\frac{a}{b} = \\frac{c}{d}",
        "correct_answer": "900",
        "solution": "Пропорция: 600/4 = x/6. x = 600 × 6/4 = 900 г.",
        "difficulty": "1",
        "tags": ["пропорция"],
    },
    {
        "topic": "quantity",
        "question": "$\\frac{3}{4} + \\frac{2}{3}$ неге тең?",
        "formula": "\\frac{a}{b} + \\frac{c}{d} = \\frac{ad+bc}{bd}",
        "correct_answer": "1.4167",
        "solution": "Ортақ бөлім 12: 9/12 + 8/12 = 17/12 ≈ 1.4167",
        "difficulty": "2",
        "tags": ["бөлшек", "қосу"],
    },
    {
        "topic": "change_and_relationships",
        "question": "Теңдеуді шешіңіз: $2x + 6 = 20$. $x$ неге тең?",
        "formula": "ax + b = c \\Rightarrow x = \\frac{c - b}{a}",
        "correct_answer": "7",
        "solution": "2x = 20 - 6 = 14. x = 14/2 = 7.",
        "difficulty": "1",
        "tags": ["сызықтық теңдеу"],
    },
    {
        "topic": "change_and_relationships",
        "question": "$x^2 - 5x + 6 = 0$ теңдеуінің түбірлерінің қосындысын табыңыз.",
        "formula": "x_1 + x_2 = -\\frac{b}{a}",
        "correct_answer": "5",
        "solution": "Виет теоремасы бойынша: x₁ + x₂ = -(-5)/1 = 5. Тексеру: D = 25-24 = 1, x = 2 және x = 3, қосындысы 5.",
        "difficulty": "3",
        "tags": ["квадрат теңдеу", "Виет теоремасы"],
    },
    {
        "topic": "change_and_relationships",
        "question": "Арифметикалық прогрессияда $a_1 = 3$, $d = 4$. $a_{10}$ табыңыз.",
        "formula": "a_n = a_1 + (n-1)d",
        "correct_answer": "39",
        "solution": "a₁₀ = 3 + (10-1)×4 = 3 + 36 = 39.",
        "difficulty": "2",
        "tags": ["прогрессия", "заңдылық"],
    },
    {
        "topic": "space_and_shape",
        "question": "Радиусы 7 см шеңбердің ауданын табыңыз. ($\\pi \\approx 3.14$)",
        "formula": "S = \\pi r^2",
        "correct_answer": "153.86",
        "solution": "S = 3.14 × 7² = 3.14 × 49 = 153.86 см².",
        "difficulty": "2",
        "tags": ["аудан", "шеңбер"],
    },
    {
        "topic": "space_and_shape",
        "question": "Тікбұрышты үшбұрыштың катеттері 3 см және 4 см. Гипотенузасын табыңыз.",
        "formula": "c = \\sqrt{a^2 + b^2}",
        "correct_answer": "5",
        "solution": "c = √(3² + 4²) = √(9 + 16) = √25 = 5 см.",
        "difficulty": "2",
        "tags": ["Пифагор теоремасы", "үшбұрыш"],
    },
    {
        "topic": "space_and_shape",
        "question": "Тікбұрышты параллелепипедтің қырлары 3, 4, 5 см. Көлемін табыңыз.",
        "formula": "V = a \\cdot b \\cdot c",
        "correct_answer": "60",
        "solution": "V = 3 × 4 × 5 = 60 см³.",
        "difficulty": "1",
        "tags": ["көлем", "параллелепипед"],
    },
    {
        "topic": "uncertainty_and_data",
        "question": "5 оқушының бойы: 155, 160, 158, 162, 165 см. Орташа бойды табыңыз.",
        "formula": "\\bar{x} = \\frac{\\sum x_i}{n}",
        "correct_answer": "160",
        "solution": "Орташа = (155 + 160 + 158 + 162 + 165) / 5 = 800 / 5 = 160 см.",
        "difficulty": "1",
        "tags": ["орташа мән", "статистика"],
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Қапта 3 қызыл, 5 көк, 2 жасыл шар бар. Кездейсоқ көк шар алу ықтималдығын табыңыз.",
        "formula": "P(A) = \\frac{m}{n}",
        "correct_answer": "0.5",
        "solution": "Барлығы: 3 + 5 + 2 = 10 шар. P(көк) = 5/10 = 0.5.",
        "difficulty": "2",
        "tags": ["ықтималдық"],
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Деректер жинағы: 2, 3, 3, 5, 7, 8, 8, 8, 10. Моданы табыңыз.",
        "correct_answer": "8",
        "solution": "Мода — ең жиі кездесетін мән. 8 саны 3 рет кездеседі — ол мода.",
        "difficulty": "1",
        "tags": ["мода", "статистика"],
    },
    {
        "topic": "change_and_relationships",
        "question": "$f(x) = 3x - 2$ функциясы үшін $f(5)$ мәнін табыңыз.",
        "formula": "f(x) = kx + b",
        "correct_answer": "13",
        "solution": "f(5) = 3 × 5 - 2 = 15 - 2 = 13.",
        "difficulty": "1",
        "tags": ["функция", "мән табу"],
    },
    {
        "topic": "space_and_shape",
        "question": "$A(1, 2)$ және $B(4, 6)$ нүктелері арасындағы қашықтықты табыңыз.",
        "formula": "d = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}",
        "correct_answer": "5",
        "solution": "d = √((4-1)² + (6-2)²) = √(9 + 16) = √25 = 5.",
        "difficulty": "3",
        "tags": ["координаталық геометрия", "қашықтық"],
    },
    {
        "topic": "quantity",
        "question": "Банкке 100 000 теңге 10% жылдық пайызбен салынды. 2 жылдан кейін қанша ақша болады? (күрделі пайыз)",
        "formula": "A = P(1 + r)^t",
        "correct_answer": "121000",
        "solution": "A = 100000 × (1 + 0.1)² = 100000 × 1.21 = 121000 теңге.",
        "difficulty": "4",
        "tags": ["күрделі пайыз", "қаржылық математика"],
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Екі сүйекті бір мезгілде лақтырғанда, қосындысы 7 болу ықтималдығы қандай?",
        "formula": "P = \\frac{m}{n}",
        "correct_answer": "0.1667",
        "solution": "Барлық жағдай: 6×6 = 36. Қосындысы 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 жағдай. P = 6/36 = 1/6 ≈ 0.1667.",
        "difficulty": "4",
        "tags": ["ықтималдық", "комбинаторика"],
    },
    {
        "topic": "space_and_shape",
        "question": "Суретте тікбұрышты үшбұрыш берілген. Катеттері 6 см және 8 см. Үшбұрыштың ауданын табыңыз.",
        "formula": "S = \\frac{1}{2} \\cdot a \\cdot b",
        "correct_answer": "24",
        "solution": "$S = \\frac{1}{2} \\cdot 6 \\cdot 8 = 24$ шаршы см.",
        "difficulty": "2",
        "tags": ["геометрия", "аудан"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Rtriangle.svg/440px-Rtriangle.svg.png",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Кестеде бес оқушының математика пәнінен алған бағалары көрсетілген. Оқушылардың орташа бағасын табыңыз.",
        "correct_answer": "4",
        "solution": "$\\bar{x} = \\frac{3+5+4+3+5}{5} = 4$",
        "difficulty": "1",
        "tags": ["статистика"],
        "table_data": {"headers": ["Оқушы", "Баға"], "rows": [["Айдар", "3"], ["Бота", "5"], ["Сара", "4"], ["Дамир", "3"], ["Еркін", "5"]], "caption": "Математика бағалары"},
    },
    {
        "topic": "space_and_shape",
        "question": "Суреттегі шеңбердің радиусы 7 см. Шеңбер ұзындығын табыңыз. ($\\pi \\approx 3.14$)",
        "formula": "C = 2\\pi r",
        "correct_answer": "43.96",
        "solution": "$C = 2 \\cdot 3.14 \\cdot 7 = 43.96$ см.",
        "difficulty": "2",
        "tags": ["геометрия", "шеңбер"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Circle-withsegments.svg/400px-Circle-withsegments.svg.png",
    },
    {
        "topic": "quantity",
        "question": "Дүкенде жемістер сатылады. Аяна 2 кг алма мен 3 кг банан сатып алды. Барлығы қанша теңге төледі?",
        "correct_answer": "3100",
        "solution": "Алма: $2 \\times 500 = 1000$ тг. Банан: $3 \\times 700 = 2100$ тг. Барлығы: $3100$ тг.",
        "difficulty": "1",
        "tags": ["арифметика", "нақты өмір"],
        "table_data": {"headers": ["Жеміс", "Бағасы (1 кг)"], "rows": [["Алма", "500 тг"], ["Банан", "700 тг"], ["Апельсин", "900 тг"], ["Алмұрт", "650 тг"]], "caption": "Жемістер бағасы"},
    },
    {
        "topic": "space_and_shape",
        "question": "Суреттегі тікбұрышты үшбұрышта бір катет 5 см, гипотенуза 13 см. Екінші катетті табыңыз.",
        "formula": "a^2 + b^2 = c^2",
        "correct_answer": "12",
        "solution": "$b = \\sqrt{13^2 - 5^2} = \\sqrt{144} = 12$ см.",
        "difficulty": "3",
        "tags": ["Пифагор теоремасы"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pythagorean.svg/390px-Pythagorean.svg.png",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Кестеде 4 мектептің оқушылар саны берілген. Орташа оқушы санын табыңыз.",
        "correct_answer": "525",
        "solution": "Жалпы: $450+600+380+670=2100$. Орташа: $\\frac{2100}{4}=525$",
        "difficulty": "2",
        "tags": ["статистика", "орташа мән"],
        "table_data": {"headers": ["Мектеп", "Оқушылар"], "rows": [["№15", "450"], ["№22", "600"], ["№8", "380"], ["№31", "670"]]},
    },
    {
        "topic": "change_and_relationships",
        "question": "Кестеде пойыздың жүру кестесі берілген. Алматыдан Астанаға дейінгі жол уақытын сағатпен табыңыз.",
        "correct_answer": "12",
        "solution": "Жөнелу: 08:00, Келу: 20:00. Жол: $20-8=12$ сағат.",
        "difficulty": "1",
        "tags": ["уақыт", "нақты өмір"],
        "table_data": {"headers": ["Бағыт", "Жөнелу", "Келу", "Қашықтық"], "rows": [["Алматы → Астана", "08:00", "20:00", "1200 км"], ["Астана → Шымкент", "10:00", "01:00", "1400 км"], ["Алматы → Тараз", "07:00", "13:00", "500 км"]], "caption": "Пойыз кестесі"},
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Қапшықта түрлі түсті шарлар бар. Қызыл шар алу ықтималдығын табыңыз (ондық бөлшек).",
        "correct_answer": "0.3",
        "solution": "Барлығы: $6+4+8+2=20$. Қызыл: 6. $P=\\frac{6}{20}=0.3$",
        "difficulty": "2",
        "tags": ["ықтималдық"],
        "table_data": {"headers": ["Түс", "Саны"], "rows": [["Қызыл", "6"], ["Көк", "4"], ["Жасыл", "8"], ["Сары", "2"]], "caption": "Қапшықтағы шарлар"},
    },
    {
        "topic": "space_and_shape",
        "question": "$A(1,2)$ және $B(4,6)$ нүктелері арасындағы қашықтықты табыңыз.",
        "formula": "d = \\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}",
        "correct_answer": "5",
        "solution": "$d=\\sqrt{9+16}=\\sqrt{25}=5$",
        "difficulty": "3",
        "tags": ["координаталық геометрия"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Cartesian-coordinate-system.svg/400px-Cartesian-coordinate-system.svg.png",
    },
    {
        "topic": "quantity",
        "question": "Бағасы 12000 теңге кроссовкаға 25% жеңілдік. Жаңа бағасын табыңыз.",
        "correct_answer": "9000",
        "solution": "Жеңілдік: $12000 \\times 0.25 = 3000$. Жаңа баға: $12000-3000=9000$ тг.",
        "difficulty": "2",
        "tags": ["пайыз", "жеңілдік"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Discount_shopping.svg/400px-Discount_shopping.svg.png",
    },
    {
        "topic": "quantity",
        "question": "Асханада түскі ас жиынтығының бағалары кестеде берілген. Айгүл 1 сорпа, 1 ет тағамы және 1 сусын алды. Ең арзан жиынтықтың бағасын табыңыз.",
        "correct_answer": "1350",
        "solution": "Ең арзан сорпа: 450, ең арзан ет: 650, ең арзан сусын: 250. Барлығы: 450+650+250 = 1350 тг",
        "difficulty": "2",
        "tags": ["нақты өмір", "бағалау"],
        "table_data": {"headers": ["Тағам", "Баға (тг)"], "rows": [["Сорпа (шұжық)", "450"], ["Сорпа (ет)", "550"], ["Ет тағамы (котлет)", "650"], ["Ет тағамы (гуляш)", "750"], ["Сусын (шай)", "250"], ["Сусын (компот)", "300"]], "caption": "Асхана мәзірі"},
    },
    {
        "topic": "quantity",
        "question": "Такси жүрісінің бағасы: отырғызу — 500 тг, әрбір км үшін — 120 тг. Айдар 12 км жүрді. Ол 2500 тг берді. Қанша қайтарым алады?",
        "correct_answer": "560",
        "solution": "Жүру құны: 500 + 120×12 = 500 + 1440 = 1940 тг. Қайтарым: 2500 - 1940 = 560 тг",
        "difficulty": "3",
        "tags": ["сызықтық модель", "нақты өмір"],
        "table_data": {"headers": ["Тариф", "Баға"], "rows": [["Отырғызу", "500 тг"], ["1 км", "120 тг"], ["Күту (1 мин)", "50 тг"]], "caption": "Такси тарифі"},
    },
    {
        "topic": "quantity",
        "question": "Дүкенде акция: 3 алсаң, 1 тегін. Нан бағасы 350 тг. Мәрият 7 нан алғысы келеді. Қанша төлейді?",
        "correct_answer": "1750",
        "solution": "7 нан = 4 + 3. Біріншіден 3 алса → 1 тегін (4 нан, 3 төлем). Қалған 3 нанның да 1-і тегін (3 нан, 2 төлем). Барлығы: 5 × 350 = 1750 тг. Тексеру: 3→+1тегін=4, тағы 3→+1тегін, бірақ 7-4=3, 3 нанның 1 тегін. 4+3=7, төлем=3+2=5. 5×350=1750",
        "difficulty": "4",
        "tags": ["логика", "акция", "нақты өмір"],
    },
    {
        "topic": "quantity",
        "question": "Зауыт өнімді 40% үстемемен сатады. Дүкен зауыттан алып, тағы 25% үстемемен сатады. Өнімнің өзіндік құны 8000 тг. Дүкендегі соңғы баға қанша?",
        "correct_answer": "14000",
        "solution": "Зауыт бағасы: 8000 × 1.4 = 11200 тг. Дүкен бағасы: 11200 × 1.25 = 14000 тг",
        "difficulty": "5",
        "tags": ["пайыз", "бизнес модель"],
    },
    {
        "topic": "change_and_relationships",
        "question": "Телефон бағасы ай сайын 5%-ға төмендейді. Бастапқы бағасы 200000 тг. 2 айдан кейінгі бағасын табыңыз.",
        "correct_answer": "180500",
        "solution": "1 ай: 200000 × 0.95 = 190000. 2 ай: 190000 × 0.95 = 180500 тг",
        "difficulty": "2",
        "tags": ["геометриялық прогрессия", "нақты өмір"],
    },
    {
        "topic": "change_and_relationships",
        "question": "Көлік А қаладан 60 км/сағ жылдамдықпен шықты. 1 сағаттан кейін көлік В 80 км/сағ жылдамдықпен соңынан шықты. В неше сағатта А-ны қуып жетеді?",
        "correct_answer": "3",
        "solution": "А алдында: 60 км. Салыстырмалы жылдамдық: 80-60=20 км/сағ. Уақыт: 60/20 = 3 сағат",
        "difficulty": "3",
        "tags": ["қозғалыс есебі", "теңдеу"],
    },
    {
        "topic": "change_and_relationships",
        "question": "Кестеде зауыттың 5 жылдағы өнім шығарылымы берілген. 2024 жылғы шығарылым 2020 жылмен салыстырғанда неше пайызға өсті?",
        "correct_answer": "50",
        "solution": "2020: 1000, 2024: 1500. Өсім: (1500-1000)/1000 × 100 = 50%",
        "difficulty": "4",
        "tags": ["деректерді талдау", "пайыздық өзгеріс"],
        "table_data": {"headers": ["Жыл", "Өнім (дана)"], "rows": [["2020", "1000"], ["2021", "1100"], ["2022", "1200"], ["2023", "1350"], ["2024", "1500"]], "caption": "Зауыт өнімділігі"},
    },
    {
        "topic": "space_and_shape",
        "question": "Суреттегі фигура L-тәрізді. Үлкен тіктөртбұрыш: 10×6 см, одан кесілген бұрыш: 4×3 см. Қалған фигураның ауданын табыңыз.",
        "correct_answer": "48",
        "solution": "Үлкен тіктөртбұрыш: 10×6=60 см². Кесілген бөлік: 4×3=12 см². Қалған аудан: 60-12=48 см²",
        "difficulty": "3",
        "tags": ["құрама фигура", "аудан"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/L-shaped_room.svg/300px-L-shaped_room.svg.png",
    },
    {
        "topic": "space_and_shape",
        "question": "Суреттегі шеңберге іштей сызылған квадраттың қабырғасы $a$ см. Шеңбер мен квадрат арасындағы аудан айырмасын табыңыз ($a=10$ см, $\\pi \\approx 3.14$).",
        "correct_answer": "57",
        "solution": "Квадрат диагоналі = шеңбер диаметрі. d = a√2 = 10√2 ≈ 14.14. r ≈ 7.07. Шеңбер ауданы: πr² ≈ 3.14×50 = 157. Квадрат ауданы: 100. Айырма: 157-100 = 57 см²",
        "difficulty": "4",
        "tags": ["шеңбер", "квадрат", "құрама"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Circled_square.svg/300px-Circled_square.svg.png",
    },
    {
        "topic": "space_and_shape",
        "question": "Үйдің жоспары берілген. Залдың ауданы 24 м², ас бөлменің ауданы 12 м², жатын бөлменің ауданы 16 м², дәлізі 6 м². Бөлмелерге плитка төсеу керек. 1 м² плитканың бағасы 3500 тг. Жалпы құнын табыңыз.",
        "correct_answer": "203000",
        "solution": "Жалпы аудан: 24+12+16+6 = 58 м². Құны: 58 × 3500 = 203000 тг",
        "difficulty": "5",
        "tags": ["нақты өмір", "аудан", "бағалау"],
        "table_data": {"headers": ["Бөлме", "Аудан (м²)"], "rows": [["Зал", "24"], ["Ас бөлме", "12"], ["Жатын бөлме", "16"], ["Дәліз", "6"]], "caption": "Пәтер жоспары"},
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Кестеде сынып оқушыларының сүйікті спорт түрлері көрсетілген. Ең танымал спорт түрін таңдаған оқушылардың жалпы оқушылар санына қатынасын пайызбен табыңыз.",
        "correct_answer": "40",
        "solution": "Ең танымал: Футбол (12). Жалпы: 12+6+8+4 = 30. Пайыз: 12/30 × 100 = 40%",
        "difficulty": "2",
        "tags": ["статистика", "пайыз", "кесте"],
        "table_data": {"headers": ["Спорт", "Оқушы саны"], "rows": [["Футбол", "12"], ["Волейбол", "6"], ["Баскетбол", "8"], ["Жүзу", "4"]], "caption": "Сүйікті спорт түрлері"},
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Кестеде 7 күндегі температура берілген. Орташа температураны және медиананы табыңыз. Жауапты медиана ретінде жазыңыз.",
        "correct_answer": "5",
        "solution": "Мәндер: -2, 0, 3, 5, 7, 8, 10. Реттелген: -2,0,3,5,7,8,10. Медиана (4-ші мән): 5°C. Орташа: (-2+0+3+5+7+8+10)/7 = 31/7 ≈ 4.43",
        "difficulty": "3",
        "tags": ["медиана", "орташа", "температура"],
        "table_data": {"headers": ["Күн", "t°C"], "rows": [["Дүйсенбі", "-2"], ["Сейсенбі", "3"], ["Сәрсенбі", "7"], ["Бейсенбі", "0"], ["Жұма", "10"], ["Сенбі", "8"], ["Жексенбі", "5"]], "caption": "Апталық ауа райы"},
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Сауалнамаға 200 оқушы қатысты. Кестеде нәтижелер берілген. Кездейсоқ таңдалған оқушы математиканы НЕМЕСЕ физиканы ұнатады деу ықтималдығын табыңыз.",
        "correct_answer": "0.65",
        "solution": "Математика: 80, Физика: 60, Екеуі де: 10. P(M∪F) = (80+60-10)/200 = 130/200 = 0.65",
        "difficulty": "4",
        "tags": ["ықтималдық", "қосу ережесі"],
        "table_data": {"headers": ["Пән", "Ұнатады", "Екеуін де"], "rows": [["Математика", "80", "10"], ["Физика", "60", "10"], ["Химия", "40", "—"], ["Биология", "20", "—"]], "caption": "Сүйікті пәндер сауалнамасы"},
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Сынақ нәтижелері кестеде берілген. Корреляцияны бағалаңыз: оқу сағаты мен балл арасында байланыс бар ма? Оқу уақыты 8 сағат болса, болжалды балл қанша?",
        "correct_answer": "80",
        "solution": "Деректерден сызықтық тренд: шамамен әр сағат +10 балл. 2→40, 4→50, 6→65, 8→? Тренд бойынша ≈80 балл",
        "difficulty": "5",
        "tags": ["корреляция", "болжам", "тренд"],
        "table_data": {"headers": ["Оқу (сағат)", "Балл"], "rows": [["2", "40"], ["4", "50"], ["6", "65"], ["10", "90"], ["12", "95"]], "caption": "Оқу уақыты мен сынақ баллы"},
    },
    {
        "topic": "quantity",
        "question": "Алматыдан Астанаға автобус билеті 5500 тг, пойыз — 8200 тг, ұшақ — 22000 тг. Отбасы (2 ересек, 1 бала — балаға 50% жеңілдік). Ұшақпен ұшса, автобуспен салыстырғанда қанша артық төлейді?",
        "correct_answer": "41250",
        "solution": "Автобус отбасы: 2×5500 + 0.5×5500 = 11000+2750 = 13750 тг. Ұшақ отбасы: 2×22000 + 0.5×22000 = 44000+11000 = 55000 тг. Айырма: 55000-13750 = 41250 тг",
        "difficulty": "3",
        "tags": ["салыстыру", "нақты өмір"],
        "table_data": {"headers": ["Көлік", "Баға (1 адам)"], "rows": [["Автобус", "5500 тг"], ["Пойыз", "8200 тг"], ["Ұшақ", "22000 тг"]], "caption": "Алматы-Астана билет бағалары"},
    },
    {
        "topic": "quantity",
        "question": "Мектеп асханасында 1 апта ішінде тамақ шығыны кестеде берілген. Орташа күндік шығынды табыңыз. Егер келесі аптада бюджет 10% қысқарса, күндік лимит қанша болады?",
        "correct_answer": "11571",
        "solution": "Жалпы: 15000+12000+13500+14000+11500+8000+7000=81000. Орташа: 81000/7≈11571. 10% қысқарту: Жаңа апталық=81000×0.9=72900. Күндік: 72900/7≈10414",
        "difficulty": "4",
        "tags": ["орташа мән", "бюджет"],
        "table_data": {"headers": ["Күн", "Шығын (тг)"], "rows": [["Дүйсенбі", "15000"], ["Сейсенбі", "12000"], ["Сәрсенбі", "13500"], ["Бейсенбі", "14000"], ["Жұма", "11500"], ["Сенбі", "8000"], ["Жексенбі", "7000"]], "caption": "Апталық тамақ шығыны"},
    },
    {
        "topic": "quantity",
        "question": "Әкесі банкке 500000 тг салды. Банк шарттары кестеде берілген. 2 жылдан кейін қай банк тиімді және айырма қанша?",
        "correct_answer": "22200",
        "solution": "А банк (10% күрделі): 500000×1.1²=605000. Б банк (12% күрделі): 500000×1.12²=627200. В банк (9% жай): 500000+90000=590000. Ең тиімді: Б банк. Айырма Б-А: 627200-605000 = 22200 тг",
        "difficulty": "5",
        "tags": ["күрделі пайыз", "қаржы"],
        "table_data": {"headers": ["Банк", "Пайыз", "Түрі"], "rows": [["А банк", "10%", "Күрделі пайыз"], ["Б банк", "12%", "Күрделі пайыз"], ["В банк", "9%", "Жай пайыз"]], "caption": "Банк депозит шарттары"},
    },
    {
        "topic": "change_and_relationships",
        "question": "Су құбырынан минутына 3 литр су ағады. Ванна сыйымдылығы 180 литр. Ванна толғаннан кейін, ағын 1 л/мин-ға азайтылса, тағы қанша минутта 60 литр қосылады?",
        "correct_answer": "60",
        "solution": "Ванна толу: 180/3=60 мин. Содан кейін 1 л/мин × t = 60 л, t = 60 мин",
        "difficulty": "3",
        "tags": ["сызықтық модель", "уақыт"],
    },
    {
        "topic": "change_and_relationships",
        "question": "Кестеде жылдар бойынша қала халқы берілген. Сызықтық тренд бойынша 2030 жылғы болжалды халық санын табыңыз (мың адам).",
        "correct_answer": "370",
        "solution": "2010→300, 2015→320, 2020→340. Әр 5 жылда +20 мың. 2025→360, 2030→380. Немесе: өсу=8 мың/жыл → 2030=340+8×10/5×2=340+30≈370",
        "difficulty": "4",
        "tags": ["тренд", "болжам"],
        "table_data": {"headers": ["Жыл", "Халық (мың)"], "rows": [["2010", "300"], ["2015", "320"], ["2020", "340"]], "caption": "Қала халқының динамикасы"},
    },
    {
        "topic": "change_and_relationships",
        "question": "Бактерия саны әр 30 минутта 2 есе өседі. Бастапқыда 100 бактерия болса, 3 сағаттан кейін қанша болады?",
        "correct_answer": "6400",
        "solution": "3 сағат = 6 рет екі еселену. 100 × 2⁶ = 100 × 64 = 6400",
        "difficulty": "5",
        "tags": ["экспоненциалды өсу", "биология"],
    },
    {
        "topic": "space_and_shape",
        "question": "Футбол алаңы 100м × 68м. Алаңның периметрі бойынша 3 айналым жүгіру керек. Жалпы қашықтықты табыңыз.",
        "correct_answer": "1008",
        "solution": "Периметр: 2(100+68) = 336 м. 3 айналым: 336×3 = 1008 м",
        "difficulty": "3",
        "tags": ["периметр", "нақты өмір"],
    },
    {
        "topic": "space_and_shape",
        "question": "Бассейн ұзындығы 25 м, ені 10 м, тереңдігі 2 м. Бассейнді суға толтыру керек. 1 м³ = 1000 л. Бассейн көлемін литрмен табыңыз.",
        "correct_answer": "500000",
        "solution": "V = 25×10×2 = 500 м³. 500 × 1000 = 500000 литр",
        "difficulty": "4",
        "tags": ["көлем", "литр"],
    },
    {
        "topic": "space_and_shape",
        "question": "Конустың биіктігі 12 см, табан радиусы 5 см. Конустың бүйір бетінің ауданын табыңыз (π≈3.14).",
        "correct_answer": "204.1",
        "solution": "Жасаушы: l = √(h²+r²) = √(144+25) = √169 = 13 см. Бүйір беті: S = πrl = 3.14×5×13 = 204.1 см²",
        "difficulty": "5",
        "tags": ["конус", "бүйір бет"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Cone_3d.png/220px-Cone_3d.png",
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Сыныпта сауалнама жүргізілді. Кестеде нәтижелер берілген. Оқушылардың қанша пайызы 7+ сағат ұйықтайды?",
        "correct_answer": "60",
        "solution": "7+ сағат: 7сағ(8) + 8сағ(10) + 9+сағ(6) = 24. Жалпы: 4+6+8+10+6+2+4 = 40. Пайыз: 24/40×100 = 60%",
        "difficulty": "3",
        "tags": ["статистика", "сауалнама"],
        "table_data": {"headers": ["Ұйқы (сағат)", "Оқушы саны"], "rows": [["5", "4"], ["6", "6"], ["7", "8"], ["8", "10"], ["9", "6"], ["10", "2"], ["10+", "4"]], "caption": "Оқушылардың ұйқы уақыты"},
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Эксперимент: 5 рет зар лақтырылды, нәтижелер: 3, 6, 2, 5, 4. Зарды тағы 1 рет лақтырғанда нәтиже 4 немесе одан жоғары болу ықтималдығын табыңыз.",
        "correct_answer": "0.5",
        "solution": "Зар жақтары: 1,2,3,4,5,6. 4 немесе одан жоғары: 4,5,6 = 3 жағдай. P = 3/6 = 0.5. Алдыңғы нәтижелер тәуелсіз.",
        "difficulty": "4",
        "tags": ["ықтималдық", "тәуелсіз оқиғалар"],
    },
    {
        "topic": "uncertainty_and_data",
        "question": "Екі топтың математика нәтижелері кестеде берілген. Қай топтың нәтижесі тұрақтырақ? Жауапты 'А' немесе 'Б' деп жазыңыз.",
        "correct_answer": "А",
        "solution": "А топ: орташа=(70+72+68+74+66)/5=350/5=70, ауытқулар кіші. Б топ: орташа=(90+50+80+40+90)/5=350/5=70, ауытқулар үлкен. А топтың дисперсиясы кіші → тұрақтырақ",
        "difficulty": "5",
        "tags": ["дисперсия", "тұрақтылық"],
        "table_data": {"headers": ["", "1-тест", "2-тест", "3-тест", "4-тест", "5-тест"], "rows": [["А топ", "70", "72", "68", "74", "66"], ["Б топ", "90", "50", "80", "40", "90"]], "caption": "Екі топтың тест нәтижелері"},
    },
    {
        "topic": "change_and_relationships",
        "question": "Кестеде температураның уақытқа байланысты өзгерісі берілген. 10 сағатта температура қанша болады, егер өзгеріс сызықтық болса?",
        "formula": "$T = 2t + 5$",
        "correct_answer": "25",
        "solution": "Кестеден заңдылық: T = 2t + 5. t = 10 болғанда: T = 2(10) + 5 = 25°C.",
        "difficulty": "3",
        "table_data": {"headers": ["Уақыт (сағ)", "Температура (°C)"], "rows": [["0", "5"], ["1", "7"], ["2", "9"], ["3", "11"], ["5", "15"]], "caption": "Температура өзгерісі"},
    },
    {
        "topic": "change_and_relationships",
        "question": "Кестеде тауардың бағасы жыл бойынша көрсетілген. 2025 жылы бағасы қанша болады, егер жыл сайынғы өсім тұрақты болса?",
        "correct_answer": "3500",
        "solution": "Жылдық өсім: 500 тг. 2024 жылы: 3000 тг. 2025 жылы: 3000 + 500 = 3500 тг.",
        "difficulty": "4",
        "table_data": {"headers": ["Жыл", "Баға (тг)"], "rows": [["2020", "1000"], ["2021", "1500"], ["2022", "2000"], ["2023", "2500"], ["2024", "3000"]], "caption": "Тауар бағасының өзгерісі"},
    },
    {
        "topic": "change_and_relationships",
        "question": "Суреттегі координата жазықтығында сызықтық функция $y = 3x - 1$ берілген. $y = 8$ болғанда $x$ нешеге тең?",
        "formula": "$y = 3x - 1$",
        "correct_answer": "3",
        "solution": "$8 = 3x - 1$, $3x = 9$, $x = 3$.",
        "difficulty": "2",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Cartesian-coordinate-system.svg/354px-Cartesian-coordinate-system.svg.png",
    },
    {
        "topic": "space_and_shape",
        "question": "Суреттегі ромбтың диагональдары 10 см және 24 см. Ромбтың ауданын табыңыз.",
        "formula": "$S = \\frac{d_1 \\cdot d_2}{2}$",
        "correct_answer": "120",
        "solution": "$S = \\frac{10 \\times 24}{2} = \\frac{240}{2} = 120$ см².",
        "difficulty": "3",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Rhombus2.svg/280px-Rhombus2.svg.png",
    },
    {
        "topic": "space_and_shape",
        "question": "Суреттегі призманың табаны тең қабырғалы үшбұрыш, қабырғасы 6 см, биіктігі 10 см. Призманың көлемін табыңыз.",
        "formula": "$V = S_{\\text{tab}} \\times h = \\frac{a^2\\sqrt{3}}{4} \\times h$",
        "correct_answer": "155.88",
        "solution": "$S_{\\text{табан}} = \\frac{6^2 \\sqrt{3}}{4} = \\frac{36 \\times 1.732}{4} \\approx 15.588$ см². $V = 15.588 \\times 10 = 155.88$ см³.",
        "difficulty": "5",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Triangular_prism.png/220px-Triangular_prism.png",
    },
]


def seed_visual_content():
    with SessionLocal() as db:
        existing_questions = {
            q.question for q in db.query(AdminTestQuestion.question).all()
        }
        existing_problems = {
            p.question for p in db.query(Problem.question).all()
        }

        added_tests = 0
        for item in ALL_TEST_QUESTIONS:
            if item["question"] in existing_questions:
                continue
            db.add(AdminTestQuestion(**item))
            existing_questions.add(item["question"])
            added_tests += 1

        added_problems = 0
        for item in ALL_PROBLEMS:
            if item["question"] in existing_problems:
                continue
            db.add(Problem(**item))
            existing_problems.add(item["question"])
            added_problems += 1

        db.commit()
        print(f"Seeded {added_tests} test questions, {added_problems} problems.")


if __name__ == "__main__":
    seed_visual_content()
